# Generated by Django 4.2.7 on 2024-04-29 10:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_rename_initial_amount_cartorderitem_initial_total'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartOder',
            new_name='CartOrder',
        ),
    ]
