# Generated by Django 5.0.4 on 2024-04-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_cart_cart_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorderitem',
            name='price',
            field=models.DecimalField(decimal_places=12, default=0.0, max_digits=12),
        ),
    ]
