# Generated by Django 4.2.7 on 2024-05-05 21:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_alter_variantitem_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WhishList',
            new_name='WishList',
        ),
    ]
